version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - APP_LOGGING_LEVEL=DEBUG
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm
    image: ewm-server-image
    container_name: ewm-server-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=ewmuser
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - STATS_SERVER_URL=http://stats-server:9090
      - APP_LOGGING_LEVEL=DEBUG
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewmuser
      - POSTGRES_USER=ewmuser
      - POSTGRES_DB=ewmdb